apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-demo-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: cdn-demo
  template:
    metadata:
      labels:
        app: cdn-demo
    spec:
      containers:
        - name: cdn-demo
          image: southamerica-west1-docker.pkg.dev/dryruns/cdn-demo/cdn-demo:latest 
          ports:
            - containerPort: 3000 
          env:
            - name: CDN_BASE_URL # Reference the environment variable from the ConfigMap
              valueFrom:
                configMapKeyRef:
                  name: cdn-config # Name of the ConfigMap
                  key: CDN_BASE_URL # Key within the ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-demo-service
spec:
  selector:
    app: cdn-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: LoadBalancer