apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-demo-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cdn-demo
  template:
    metadata:
      labels:
        app: cdn-demo
    spec:
      containers:
        - name: cdn-demo
          image: southamerica-west1-docker.pkg.dev/dryruns/cdn-demo/cdn-demo:latest # Use the correct image tag
          ports:
            - containerPort: 8080 # Expose the port your Spring Boot app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-demo-service
spec:
  selector:
    app: cdn-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Map the service port to the container port
  type: LoadBalancer 